name: Android Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Haxe and OpenFL
      uses: skial/setup-haxe@v1
      with:
        haxe-version: 4.2.5
        haxelib-version: latest
        openfl-version: latest

    - name: Install Dependencies
      run: haxelib run lime build android -notests

    - name: Execute Custom Commands
      run: haxe -cp commandline -D analyzer-optimize --run Main setup

    - name: Build Android Project
      run: haxelib run lime build android

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: export/release/android/bin
